### ISSUE TITLE
Multiple assignment of ggplot2 objects

### ISSUE THREAD

**Issue by llrs** [nteetor/zeallot#39] opened 2018-02-03 10:36 UTC
Nice package, thanks for bringing multiple assignments into R I like that feature of python.

I have read this issue https://github.com/thomasp85/patchwork/issues/32, and I tried to create a plot and then use multiple assignments to reorder the appearance using the mentioned package. However `%<-%` couldn't would it be possible to work like this:

```
c(setosa, versicolor, virginica) %<-% ggplot(iris) + 
    geom_point(aes(Sepal.Length, Sepal.Width)) + 
    facet_wrap(~Species)
Error: invalid `%<-%` right-hand side, incorrect number of values
```
Maybe the issue is how to handle gg and ggplot classes, but I am not enough familiar with gg classes to propose a solution (or to know if it is feasable). 

Again thanks
(I was using the version of zeallot from CRAN, `zeallot_0.1.0 ggplot2_2.2.1`)

**Comment by nteetor** [comment] 2018-02-03 16:16
I think the problem is twofold. First, the custom arrow operator does not yet know how to handle a ggplot object. You will need to implement a `destructure.gg` or `destructure.ggplot` method, see `?destructure`. The implementation would return a list of the elements of a ggplot objects. 

Naively, that function might look like,
```R
destructure.ggplot <- function(x) {
  lapply(x, identity)
}
```

Once you have created an implementation you can use `.` and `...` to skip unneeded elements and selectively assign the ggplot elements you are interested in. The second and smaller consideration concerns operator precedence. The `%<-%` operator takes precedence over the binary `+` operator. So be sure to wrap parentheses around the ggplot expression or you may get unexpected results.

**Comment by llrs** [comment] 2018-02-05 10:10
Maybe it is something worth of checking but [ggforce](https://cran.r-project.org/package=ggforce) and its `facet_wrap_paginate` allows to split a facet_wrap into several pages which is close to what I had asked for.

**Comment by nteetor** [comment] 2018-02-05 14:24
Nice! If you do not have to reinvent the wheel by all means don't. I'll close this issue for now, but we can reopen the issue if need be.

**Closed as completed by nteetor** 2018-02-05 14:24 UTC
